/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GameRentalStore;

import javax.swing.JOptionPane;

/**
 *
 * @author Mohammed Azzam
 */
public class Add extends javax.swing.JFrame {
    CollectionOfGames game=new CollectionOfGames();
    /**
     * Creates new form Add
     */
    public Add() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComapnyBTN = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        AvailabilityBTN = new javax.swing.JComboBox<>();
        namebtn = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DescriptionBTN = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1290, 695));
        getContentPane().setLayout(null);

        ComapnyBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComapnyBTNActionPerformed(evt);
            }
        });
        getContentPane().add(ComapnyBTN);
        ComapnyBTN.setBounds(740, 240, 270, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2016", "2015", "2014", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(310, 330, 130, 30);

        AvailabilityBTN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Not Available yet" }));
        AvailabilityBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvailabilityBTNActionPerformed(evt);
            }
        });
        getContentPane().add(AvailabilityBTN);
        AvailabilityBTN.setBounds(780, 340, 150, 30);

        namebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namebtnActionPerformed(evt);
            }
        });
        getContentPane().add(namebtn);
        namebtn.setBounds(310, 250, 230, 30);

        jButton1.setFont(new java.awt.Font("Champagne & Limousines", 1, 24)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(550, 610, 170, 40);

        jButton2.setFont(new java.awt.Font("Champagne & Limousines", 1, 18)); // NOI18N
        jButton2.setText("Goback");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1170, 10, 100, 30);

        jButton14.setFont(new java.awt.Font("Champagne & Limousines", 1, 18)); // NOI18N
        jButton14.setText("Log Out");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14);
        jButton14.setBounds(1060, 10, 100, 30);

        jLabel5.setFont(new java.awt.Font("Champagne & Limousines", 1, 52)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Add Games");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(500, 100, 330, 90);

        jLabel1.setFont(new java.awt.Font("Orator Std", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Year");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 330, 190, 40);

        jLabel2.setFont(new java.awt.Font("Orator Std", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 250, 130, 40);

        jLabel3.setFont(new java.awt.Font("Orator Std", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Description");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 420, 270, 40);

        jLabel6.setFont(new java.awt.Font("Orator Std", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Platform");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(190, 550, 220, 40);

        DescriptionBTN.setColumns(20);
        DescriptionBTN.setRows(5);
        jScrollPane1.setViewportView(DescriptionBTN);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(450, 420, 330, 110);

        jLabel7.setFont(new java.awt.Font("Orator Std", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Company");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(580, 240, 190, 40);

        jLabel8.setFont(new java.awt.Font("Orator Std", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("availability");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(500, 330, 290, 40);

        jRadioButton1.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(240, 240, 240));
        jRadioButton1.setText("XBOX ONE");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(620, 550, 170, 40);

        jRadioButton2.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(240, 240, 240));
        jRadioButton2.setText("Playstation 4");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(410, 550, 170, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GameRentalStore/adminbackground.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1280, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        StaffMenu s = new StaffMenu();
        s.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        Stafflogin s = new Stafflogin();
        s.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if (DescriptionBTN.getText().equals("")|| ComapnyBTN.getText().equals("")|| namebtn.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Error Try Again");
        }
        
        else
        {
            JOptionPane.showMessageDialog(null,"Game Modified");
        
        
        String company=ComapnyBTN.getText();
        String name=namebtn.getText();
        String year=jComboBox1.getActionCommand();
        float r=Float.parseFloat(year);
        String disc=DescriptionBTN.getText();
        String ava=AvailabilityBTN.getActionCommand();
        
        Admin s=new Admin();
        if (s.GameStore(name,company,r,disc,ava)){
            JOptionPane.showMessageDialog(null,"Game Modified");
        }
        else{
          JOptionPane.showMessageDialog(null,"Error","Error",JOptionPane.ERROR_MESSAGE);

        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void AvailabilityBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvailabilityBTNActionPerformed
        // TODO add your handling code here:
        
        String name=AvailabilityBTN.getActionCommand();
        game.setGameAvailability(name);
    }//GEN-LAST:event_AvailabilityBTNActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void namebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namebtnActionPerformed
        // TODO add your handling code here:
        
        String name=namebtn.getText();
        game.setGamename(name);
        
    }//GEN-LAST:event_namebtnActionPerformed

    private void ComapnyBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComapnyBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComapnyBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AvailabilityBTN;
    private javax.swing.JTextField ComapnyBTN;
    private javax.swing.JTextArea DescriptionBTN;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField namebtn;
    // End of variables declaration//GEN-END:variables
}
